ARG VERSION
ARG REGISTRY
ARG SPARK_IMAGE=${REGISTRY}bn-spark-operator/spark:v${VERSION}

# not re-build, just copy from ...
FROM ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.8-3.1.1 as builder

FROM ${SPARK_IMAGE}
USER root
COPY --from=builder /usr/bin/spark-operator /usr/bin/
COPY --from=builder /usr/bin/gencerts.sh /usr/bin/
COPY --from=builder /usr/bin/entrypoint.sh /usr/bin/
RUN apt-get update --allow-releaseinfo-change \
    && apt-get update \
    && apt-get install -y openssl curl tini \
    && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
