apiVersion: spark.bytenative.com/v1
kind: SparkJob
metadata:
  name: job-spark-sqlfile-341
  namespace: sparkjobs
spec:
  spark:
    sparkVersion: "3.4.1"
    mode: cluster
    imagePullPolicy: IfNotPresent
    image: bnp.me/bn-spark-operator/spark:v3.4.1
    restartPolicy:
      type: Never
    volumes:
      - name: "spark-local-dir-test-volume"
        emptyDir: {}
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        version: 3.4.1
      serviceAccount: spark-runner-spark
      volumeMounts:
        - name: "spark-local-dir-test-volume"
          mountPath: "/tmp/local-test"
    executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        version: 3.4.1
      volumeMounts:
        - name: "spark-local-dir-test-volume"
          mountPath: "/tmp/local-test"
    sparkUIOptions:
      servicePort: 9090
      servicePortName: "spark-driver-ui-port"
      serviceType: NodePort
    s3Connection:
      inline:
        host: minio.default.svc.cluster.local
        port: 9000
        accessStyle: Path
        credentials:
          # secret: s3-connection
          inline:
            accessKey: minio
            secretKey: miniopass

  job:
    type: SqlFileJob
    sqlFile: s3a://spark-deps/sql/examples/tripdata-report.sql